### ISSUE TITLE
MVP UI

### ISSUE THREAD

**Issue by benji1298** [MaxBuster/communicare-front#1]
- [x] Registration @MaxBuster PR #2
- [x] Login @MaxBuster PR #3 
- [x] Set-up Tent @benji1298 PR #6 
- [ ] Tent Diagnostics @MaxBuster
- [ ] Add/Receive Supplies
- [ ] Consume/Request Supplies
- [ ] Data Viz @makenabarickman
